apiVersion: v1
kind: Namespace
metadata:
  name: movie-app

---
# =======================
# MOVIE DATABASE (Stateful)
# =======================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  namespace: movie-app
spec:
  serviceName: movie-db
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: movie_db_username
            - name: POSTGRES_PASSWORD
              value: movie_db_password
            - name: POSTGRES_DB
              value: movie_db_dev
          volumeMounts:
            - name: movie-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: movie-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: movie-app
spec:
  clusterIP: None
  selector:
    app: movie-db
  ports:
    - port: 5432
      targetPort: 5432

---
# =======================
# CAST DATABASE (Stateful)
# =======================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
  namespace: movie-app
spec:
  serviceName: cast-db
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: cast_db_username
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_DB
              value: cast_db_dev
          volumeMounts:
            - name: cast-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: cast-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: movie-app
spec:
  clusterIP: None
  selector:
    app: cast-db
  ports:
    - port: 5432
      targetPort: 5432

---
# =======================
# MOVIE SERVICE (FastAPI)
# =======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: rajabm1311/movie-image:v.93.0
          #command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio", "--workers", "1"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
            - name: CAST_SERVICE_HOST_URL
              value: http://cast-service:8000/api/v1/casts/

---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: movie-app
spec:
  selector:
    app: movie-service
  ports:
    - port: 8000
      targetPort: 8000

---
# =======================
# CAST SERVICE (FastAPI)
# =======================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: rajabm1311/cast-image:v.93.0
          #command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio", "--workers", "1"]
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev

---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: movie-app
spec:
  selector:
    app: cast-service
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: nginx-config-volume
          hostPath:
            path: /home/ubuntu/Jenkins_devops_exams/nginx_config.conf  # Absolute path to the config file, path only doesn't work
            type: File  # Explicitly specify it's a file

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: movie-app
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30669
