{{- if .Values.castService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.castService.replicas }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: {{ .Values.castService.image }}
          imagePullPolicy: {{ .Values.castService.imagePullPolicy }}
          command: 
            - "uvicorn"
            - "app.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--loop"
            - "asyncio"
            - "--workers"
            - "1"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://{{ .Values.castDb.username }}:{{ .Values.castDb.password }}@cast-db/{{ .Values.castDb.database }}"
          resources:
            {{- toYaml .Values.castService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: cast-service
  ports:
    - port: 8000
      targetPort: 8000
{{- if .Values.castService.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cast-service-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cast-service
  minReplicas: {{ .Values.castService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.castService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.castService.autoscaling.targetCPU }}
{{- end }}
{{- end }}
