{{- if .Values.movieDb.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: movie-db
  replicas: {{ .Values.movieDb.replicas }}
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: "{{ .Values.postgresImage.repository }}:{{ .Values.postgresImage.tag }}"
          imagePullPolicy: {{ .Values.postgresImage.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.movieDb.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.movieDb.password }}
            - name: POSTGRES_DB
              value: {{ .Values.movieDb.database }}
          volumeMounts:
            - name: movie-db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.movieDb.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: movie-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.movieDb.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: movie-db
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
