{{- if .Values.movieService.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.movieService.replicas }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: {{ .Values.movieService.image }}
          imagePullPolicy: {{ .Values.movieService.imagePullPolicy }}
          command: 
            - "uvicorn"
            - "app.main:app" 
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--loop"
            - "asyncio"
            - "--workers"
            - "1"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://{{ .Values.movieDb.username }}:{{ .Values.movieDb.password }}@movie-db/{{ .Values.movieDb.database }}"
            - name: CAST_SERVICE_HOST_URL
              value: "http://cast-service:8000/api/v1/casts/"
          resources:
            {{- toYaml .Values.movieService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: movie-service
  ports:
    - port: 8000
      targetPort: 8000
{{- if .Values.movieService.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-service-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-service
  minReplicas: {{ .Values.movieService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.movieService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.movieService.autoscaling.targetCPU }}
{{- end }}
{{- end }}
